<?php

namespace Staff\Controllers;

use Staff\Controllers\ControllerBase;
use Staff\Forms\ArticleForm;
use Staff\Models\Articles;

class ArticlesController extends ControllerBase
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

       // $this->view->setTemplateAfter('form-register');
    }

    public function indexAction()
    {

    }

    public function createAction()
    {
        $success = false;
        $form = new ArticleForm();
        $article = new Articles();
        $data = $this->request->getPost();
        if ($this->request->isPost()){
            $form->bind($data, $article);
            if (!$form->isValid()){
               $this->flash->warning('Поля не валидными пожалуйста заполните их правельно!');
                $success = false;
            }else{
                try{
                    if($article->save()){
                        $success = true;
                        $this->flashSession->success('Статья была успешно создана!');
                    }
                }catch (\Exception $e){
                    $this->flash->error('Данная статья с такими данными уже существует, все поля или одно из них содержит уже существующий материал в базе!');
                }
            }
        }

        $this->view->success = $success;
        $this->view->setVar('form',$form);
    }

    public function editAction()
    {


    }
    public function AddAction()
    {

    }


}

